# 可选择性监控配置
monitoring:
  enabled: true
  cve: true
  github: true
  articles: false
  auto_analyze: true

# Redis配置
redis:
  enabled: true  # 设置为false，避免在没有Redis的环境下尝试连接
  url: "redis://localhost:6379/0"  # Redis连接URL
  queue: "threatvision_queue"  # Redis队列名称

# GitHub 监控关键词
github_keywords:
  - 'CVE-2024'
  - 'CVE-2025'
  - 'exploit'
  - 'vulnerability'
  - '0day'
  - 'poc&exp'
  - 'RCE'
  - 'bypass&绕过'

# 重点监控仓库列表 (owner/repo)
watched_repositories:
  - 'projectdiscovery/nuclei-templates'
  - 'rapid7/metasploit-framework'
  - 'adysec/nuclei_poc'


# RSS/OPML Configuration
rss:
  CyberSecurityRSS:
    enabled: false
    url: "https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/CyberSecurityRSS.opml"
    filename: "CyberSecurityRSS.opml"
  CyberSecurityRSS-tiny:
    enabled: false
    url: "https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/tiny.opml"
    filename: "CyberSecurityRSS-tiny.opml"
  Chinese-Security-RSS:
    enabled: true
    url: "https://raw.githubusercontent.com/zhengjim/Chinese-Security-RSS/master/Chinese-Security-RSS.opml"
    filename: "Chinese-Security-RSS.opml"
  awesome-security-feed:
    enabled: false
    url: "https://raw.githubusercontent.com/mrtouch93/awesome-security-feed/main/security_feeds.opml"
    filename: "awesome-security-feed.opml"
  wechatRSS:
    enabled: false
    url: "https://wechat2rss.xlab.app/opml/sec.opml"
    filename: "wechatRSS.opml"
  chinese-independent-blogs:
    enabled: false
    url: "https://raw.githubusercontent.com/timqian/chinese-independent-blogs/master/feed.opml"
    filename: "chinese-independent-blogs.opml"
